Work in progress: Adding CloseConnectionsOnDelete flag
skupperproject/skupper pull request #1564
Opened 2024-07-31 20:17 UTC by Karen-Schoener

2024-08-02 15:31 UTC, gabordozsa requested changes
@Karen-Schoener I cannot see how the value of the new flag gets into the intialRouterConfig. I would expect some extra code around here: https://github.com/skupperproject/skupper/blob/fca6f869c89dc83ccadc74202a9a137e1a732ea9/pkg/qdr/qdr.go#L72.  I think the new flag  should be handled similarly to `DataConnectionCount` parameter and it needs to be added to the `routerConfig.Metadata` here.

2024-08-02 17:58 UTC, ajssmith commented on api/types/client.go
> +	CloseConnectionsOnDelete bool
In perusing similar settings in firewall implementations, we might consider a flag name along the lines of:

DropActiveTcpConnections
or
TerminateActiveTcpConnections

I would lean towards not having the "OnDelete" suffix as the action is implicit and will be reflected in documentation, etc.

2024-08-02 18:00 UTC, ajssmith commented on api/types/client.go
> +	CloseConnectionsOnDelete bool
Or more simply "DropTcpConnections" as the active is implied...

2024-08-02 18:03 UTC, ajssmith commented
Agree with @gabordozsa that update to the initial router config should be part of this change. As identified, should be addition to setting of RouterConfig metadata in qdr.go

2024-08-02 18:33 UTC, Karen-Schoener commented
> Agree with @gabordozsa that update to the initial router config should be part of this change. As identified, should be addition to setting of RouterConfig metadata in qdr.go

Added new configurable to RouterMetadata. 

I will plan to make another checkin with the suggestion: rename param to DropTcpConnections.

2024-08-02 18:45 UTC, Karen-Schoener commented on api/types/client.go
> +	CloseConnectionsOnDelete bool
Renamed new param to: DropTcpConnections

2024-08-05 17:18 UTC, gabordozsa approved these changes
LGTM

2024-08-06 14:11 UTC, merged